config/routes.rb
Vcard::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  scope :module => "admin" do
    match '/my_site' => 'admin_main#main'
    resources :rubrics
    resources :articles
    resources :subscribes
  end

  devise_for :users

  get "support/change_language"

  root :to => 'home#index'

  scope "(:locale)", :locale => /en|ru/ do
    match '/' => 'home#index'
    match '/about' => 'home#about'
    match '/resume' => 'home#resume'
    match '/contact' => 'home#contact'
    match '/blog' => 'home#blog'
    match '/blog/subscribe' => 'blog#subscribe', :as => :subscribe_to_blog
    match '/blog/unsubscribe/:id' => 'blog#unsubscribe', :as => :unsubscribe_from_blog
    match '/blog/:id' => 'blog#show_rubric', :as => :show_rubric
    match '/blog/article/:id' => 'blog#show_article', :as => :show_article
    match '/change_language' => 'home#change_language'
    match '/contact/send_email' => 'contact#send_email'
  end

  match "*a", :to => "blog#routing_error"

end

app/models/subscribe.rb
class Subscribe < ActiveRecord::Base
  attr_accessible :email, :language
  validates :email, :presence => true,
            :format => {:with => /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i},
            :uniqueness => true

  scope :for_language, lambda{|l_a| where("language IN (?) OR language = 'all'", l_a)}
end

app/controllers/admin/subscribes_controller.rb
class Admin::SubscribesController < Admin::ApplicationController

  def index
    @subscribes = Subscribe.page(params[:page])
  end

  def show
    @subscribe = Subscribe.find(params[:id])
  end

  def new
    @subscribe = Subscribe.new
  end

  def edit
    @subscribe = Subscribe.find(params[:id])
  end

  def create
    @subscribe = Subscribe.new(params[:subscribe])
    if @subscribe.save
      redirect_to @subscribe, notice: 'Subscribe was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @subscribe = Subscribe.find(params[:id])
    if @subscribe.update_attributes(params[:subscribe])
      redirect_to @subscribe, notice: 'Subscribe was successfully updated.'
    else
      render action: "edit"
    end
  end


  def destroy
    @subscribe = Subscribe.find(params[:id])
    @subscribe.destroy
    redirect_to subscribes_url
  end

end

app/helpers/admin/subscribes_helper.rb
module Admin::SubscribesHelper
end

app/views/admin/subscribes/_form.html.erb
<%= form_for(@subscribe) do |f| %>

    <%= form_field(f, :text_field, :email) %>

    <div style="padding: 5px 0 10px 0; line-height: 1.6em; ">
      <label>Language</label>
      <%= f.select :language, options_for_select(
              [['All languages', ''],
               ['English', 'en'],
               ['Russian','ru']]) %>
    </div>
    <%= f.submit "Save", :class => 'button' %>

<% end %>

app/views/admin/subscribes/edit.html.erb
<h1>Editing admin_subscribe</h1>
<%= render :partial => 'admin/shared/form_errors', :locals => {:object => @subscribe} %>

<%= render 'form' %>

<%= link_to 'Show', @subscribe %> |

app/views/admin/subscribes/index.html.erb
<h2>Subscribers Index</h2>
<a class="shortcut-button" href="<%= new_subscribe_path %>">
  <span>
    <%= image_tag 'images/pencil_big.png' %> <br/>
	Add a Subscriber
  </span>
</a>
<div style="width: 40%">
  <%= render :partial => 'admin/shared/notifications' %>
</div>

<div class="content-box" style="width: 60%">
  <table>
    <thead>
    <tr>
      <th>Email</th>
      <th>Language</th>
      <th width="60px;">Actions</th>
    </tr>
    </thead>

    <tfoot>
    <tr>
      <td colspan="2">
        <%= paginate @subscribes %>
        <br/>
        <div class="clear"></div>
      </td>
    </tr>
    </tfoot>

    <tbody>
    <% if @subscribes.any? %>
        <% @subscribes.each do |subscribe| %>
            <tr>
              <td><%= subscribe.email %></td>
              <td><%= subscribe.language.presence || 'All languages' %></td>
              <td>
                <%= link_to '', edit_subscribe_path(subscribe), :class => 'edit_link' %>
                <%= link_to '', subscribe_path(subscribe), :class => 'destroy_link', :method => :delete,
                            :confirm => "Are sure you want to delete #{subscribe.email}?" %>
              </td>
            </tr>
        <% end %>

    <% else %>
        <tr>
          <td colspan="3">
            There is no subscribers yet. Please click "Add a Subscriber" to add new one.
          </td>
        </tr>
    <% end %>

    </tbody>

  </table>
</div>

app/views/admin/subscribes/new.html.erb
<h1>New Subscriber</h1>
<%= render :partial => 'admin/shared/form_errors', :locals => {:object => @subscribe} %>

<%= render 'form' %>

app/views/admin/subscribes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @subscribe.email %>
</p>


<%= link_to 'Edit', edit_subscribe_path(@subscribe) %> |
<%= link_to 'Back', subscribes_path %>