config/routes.rb
Vcard::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  scope :module => "admin" do
    match '/my_site' => 'admin_main#main'
    resources :rubrics
    resources :articles
    resources :subscribes
  end

  devise_for :users

  get "support/change_language"

  root :to => 'home#index'

  scope "(:locale)", :locale => /en|ru/ do
    match '/' => 'home#index'
    match '/about' => 'home#about'
    match '/resume' => 'home#resume'
    match '/contact' => 'home#contact'
    match '/blog' => 'home#blog'
    match '/blog/subscribe' => 'blog#subscribe', :as => :subscribe_to_blog
    match '/blog/unsubscribe/:id' => 'blog#unsubscribe', :as => :unsubscribe_from_blog
    match '/blog/:id' => 'blog#show_rubric', :as => :show_rubric
    match '/blog/article/:id' => 'blog#show_article', :as => :show_article
    match '/change_language' => 'home#change_language'
    match '/contact/send_email' => 'contact#send_email'
  end

  match "*a", :to => "blog#routing_error"

end

app/models/rubric.rb
class Rubric < ActiveRecord::Base
  extend FriendlyId
  include Modules::ModelTranslation
  friendly_id :title_en, use: :slugged

  has_and_belongs_to_many :articles, :uniq =>true
  validates :title_en, :title_ru, :uniqueness => true, :presence => true

  scope :with_published_articles, joins(:articles).where("articles.original_id IS NOT NULL")

  paginates_per 5
end

app/controllers/admin/rubrics_controller.rb
class Admin::RubricsController < Admin::ApplicationController

  def index
    @rubrics = Rubric.where('1=1').page(params[:page])
  end

  def new
    @rubric = Rubric.new
  end

  def create
    @rubric = Rubric.new(params[:rubric])
    if @rubric.save
      redirect_to rubrics_path, :success => "New Rubric was successfully added."
    else
      render :new
    end
  end

  def edit
    @rubric = Rubric.find(params[:id].to_i)
  end

  def update
    @rubric = Rubric.find(params[:id].to_i)
    if @rubric.update_attributes(params[:rubric])
      redirect_to rubrics_path, :success => "New Rubric was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @rubric = Rubric.find(params[:id])
    @rubric.destroy
    redirect_to rubrics_path, :notice => "Rubric was successfully deleted."
  end
end

app/helpers/admin/rubrics_helper.rb
module Admin::RubricsHelper
end

app/views/admin/rubrics/_form.html.erb
<%= form_for @rubric do |f| %>

    <%= form_field(f, :text_field, :title_en) %>
    <%= form_field(f, :text_field, :title_ru) %>

    <%= f.submit "Save", :class => 'button' %>
<% end %>

app/views/admin/rubrics/_rubric.html.erb
<tr>
  <td><%= rubric.title_ru %></td>
  <td><%= rubric.title_en %></td>
  <td>
    <%= link_to '', edit_rubric_path(rubric), :class => 'edit_link' %>
    <%= link_to '', rubric_path(rubric), :class => 'destroy_link', :method =>  :delete,
                :confirm => "Are sure you want to delete #{rubric.title_en}?" %>
  </td>
</tr>

app/views/admin/rubrics/edit.html.erb
<h2>Edit Rubric</h2>
<%= render :partial => 'admin/shared/form_errors', :locals => {:object => @rubric} %>
<%= render 'form' %>

app/views/admin/rubrics/index.html.erb
<h2>Rubrics Index</h2>
<a class="shortcut-button" href="<%= new_rubric_path %>">
  <span>
    <%= image_tag 'images/pencil_big.png' %> <br/>
	Add a Rubric
  </span>
</a>
<div style="width: 50%">
  <%= render :partial => 'admin/shared/notifications' %>
</div>

<div class="content-box" style="width: 50%">
  <table>
    <thead>
    <tr>
      <th>Title ru</th>
      <th>Title en</th>
      <th width="60px;">Actions</th>
    </tr>
    </thead>

    <tfoot>
    <tr>
      <td colspan="3">
        <%= paginate @rubrics %><br/>
        <div class="clear"></div>
      </td>
    </tr>
    </tfoot>

    <tbody>
    <% if @rubrics.any? %>
        <%= render :partial => 'rubric', :collection => @rubrics %>
    <% else %>
        <tr>
          <td colspan="3">
            There is no rubrics yet. Please click "Add a Rubric" to add new one.
          </td>
        </tr>
    <% end %>

    </tbody>

  </table>
</div>