config/routes.rb
Vcard::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  scope :module => "admin" do
    match '/my_site' => 'admin_main#main'
    resources :rubrics
    resources :articles
    resources :subscribes
  end

  devise_for :users

  get "support/change_language"

  root :to => 'home#index'

  scope "(:locale)", :locale => /en|ru/ do
    match '/' => 'home#index'
    match '/about' => 'home#about'
    match '/resume' => 'home#resume'
    match '/contact' => 'home#contact'
    match '/blog' => 'home#blog'
    match '/blog/subscribe' => 'blog#subscribe', :as => :subscribe_to_blog
    match '/blog/unsubscribe/:id' => 'blog#unsubscribe', :as => :unsubscribe_from_blog
    match '/blog/:id' => 'blog#show_rubric', :as => :show_rubric
    match '/blog/article/:id' => 'blog#show_article', :as => :show_article
    match '/change_language' => 'home#change_language'
    match '/contact/send_email' => 'contact#send_email'
  end

  match "*a", :to => "blog#routing_error"

end

app/views/shared/_blog_title.html.erb
<% if defined?(title) %>
    <% if defined?(url) && defined?(link_text) %>
        <%= link_to link_text, url, :class => 'left bold white_text back_link' %>
    <% end %>
    <% if defined?(subscribe_url) && defined?(subscribe_link_text) %>
        <%#= link_to subscribe_link_text, 'javascript:void(0);', :class => 'right bold white_text subscribe_link', :onclick => 'open_subscribe_dialog();' %>
    <% end %>
    <h3 class="center_align">
      <%= title %>
    </h3>

    <div id="subscribe_dialog" style="display: none;">
      <%= form_tag subscribe_to_blog_url(:locale => I18n.locale), :remote => true, :id => 'subscribe_form' do |f| %>
          <div class="form_row">
            <label for="subscriber_email"><%= t('subscribe_form.email') %><star class='red'>*</star>:</label>
            <%= text_field_tag "subscriber[email]" %>
            <div class="clear"></div>
            <div class="error_row"></div>
          </div>
          <div class="form_row">
            <label for="subscriber_language"><%= t('subscribe_form.language') %><star class='red'>*</star>:</label>
            <%= select_tag 'subscriber[language]', options_for_select(
                  [[t('subscribe_form.all_languages'), 'all'],
                   [t('subscribe_form.en_language'), 'en'],
                   [t('subscribe_form.ru_language'),'ru']], :selected =>  I18n.locale.to_s) %>
            <div class="clear"></div>
            <div class="error_row"></div>
          </div>
          <hr/>
          <div class="subscribe_notification">
              <%= t('subscribe_form.unsubscribe_notification') %>
          </div>
      <% end %>
    </div>

    <script type="text/javascript">
        $(function () {
            $('#subscribe_dialog').dialog({ modal:true, resizable:false, autoOpen:false,
                title:'<%= t(:subscribe_dialog) %>', width:400,
                buttons:[
                    {
                        text:'<%= t('helpers.links.subscribe') %>',
                        click:function () {
                            show_loading();
                            $('#subscribe_dialog').dialog('close');
                            $('#subscribe_form').submit();
                        }
                    },
                    {
                        text:'<%= t(:cancel) %>',
                        click:function () {
                            $(this).dialog('close');
                        }
                    }
                ]})
        })

        function open_subscribe_dialog() {
            $('#subscribe_dialog').dialog('open');
        }
    </script>
<% end %>

app/views/shared/_loading_gif.html.erb
<div id="loading_gif" style="display: none; position: absolute; background-color: transparent; z-index: 1002;">
  <img src='/image/loading_small.gif'/>
</div>

<script type="text/javascript">
    $(function () {
        $('#loading_gif').load('/loading_mult.html')
    })
</script>

app/views/shared/_system_dialog.html.erb
<div id="system_dialog" style="display: none;"></div>

<script type="text/javascript">
    $(function () {
        $('.scroll_box').jScrollPane();
        $('#system_dialog').dialog({ modal:true, resizable:false, autoOpen:false,
            title:'<%= t(:system_dialog) %>', width:330,
            buttons:[
                {
                    text:'Ok',
                    click:function () {
                        $(this).dialog('close')
                    }
                }
            ]});
        <% if params[:system_message] %>
            $('#system_dialog').html("<%=  params[:system_message] %>");
            $('#system_dialog').dialog('open');
        <% end %>
    })
</script>